version: 1
name: "learning-compose-example-1"

services:
  box:
    image: busybox
    command: ["echo", "I'm running ${COMPOSE_PROJECT_NAME}"]

    environment:
      - VALUE=${X?error "X is not defined in ${COMPOSE_PROJECT_NAME}"}
